[tool.ruff]
line-length = 120
indent-width = 4
extend-include = ["*.ipynb"]
extend-exclude = ["notebooks/*"]
target-version = "py312"

[[tool.mypy.overrides]]
module = "s3fs"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "transformers"
ignore_missing_imports = true

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
#ignore  = ["B024"]

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = [
    "src.config.DefaultFullConfig"
]

[tool.ruff.format]
indent-style = "space"
