[tool.ruff]
line-length = 120
extend-include = ["*.ipynb"]
extend-exclude = ["notebooks/*"]
target-version = "py312"

[[tool.mypy.overrides]]
module = "s3fs"
ignore_missing_imports = true

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
ignore  = ["B024"]
