apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-insee-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-insee-data
  template:
    metadata:
      labels:
        app: rag-insee-data
    spec:
      containers:
        - name: api
          image: linogaliana/llm-statbot:app
          command: ["uv", "run", "streamlit", "run", "app.py"]
          args: ["--", "--use_vault", "False"]
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: statbot-secret
            - secretRef:
                name: sa-s3-statbot
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "50Gi"
              cpu: "30"
