apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rag-insee-data-unece
spec:
  tls:
    - hosts:
        - rag-insee-demo-unece.lab.sspcloud.fr
  rules:
    - host: rag-insee-demo-unece.lab.sspcloud.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rag-insee-data-unece
                port:
                  number: 80


