# S3 CONFIG -------------------------------------------------------------------

experiment_name = "default"
# aws_s3_endpoint = "minio.lab.sspcloud.fr"
s3_bucket = "projet-llm-insee-open-data"
s3_endpoint_url = "https://{aws_s3_endpoint}" # (templated)

# LOCAL FILES -----------------------------------------------------------------

work_dir = "."
relative_data_dir = "data"
relative_logs_dir = "logs"
data_dir_path = "{work_dir}/{relative_data_dir}" # (templated)
logs_dir_path = "{work_dir}/{relative_logs_dir}" # (templated)

# ML FLOW LOGGING -------------------------------------------------------------

mlflow_tracking_uri = "https://projet-llm-insee-open-data-mlflow.user.lab.sspcloud.fr"

# MLflow run ID to override all parameters with
# mlflow_run_id = ""
# Should artifacts (Chroma DB) also be loaded from MLflow
mlflow_load_artifacts = true

# RAW DATA PROCESSING  --------------------------------------------------------

data_raw_s3_path = "data/raw_data/applishare_solr_joined.parquet"
raw_dataset_uri = "s3://{s3_bucket}/{data_raw_s3_path}" # (templated)
markdown_split = true
use_tokenizer_to_chunk = true
separators = ['\n\n', '\n', '.', ' ', '']

rawdata_web4g = "data/raw_data/applishare_solr_joined.parquet"
rawdata_rmes = "data/raw_data/applishare_solr_joined.parquet"
rawdata_web4g_uri = "s3://{s3_bucket}/{rawdata_web4g}" # (templated)
rawdata_rmes_uri = "s3://{s3_bucket}/{rawdata_rmes}" # (templated)

# PARSING, PROCESSING and CHUNKING CORPUS -------------------------------------

max_pages     = "None"  # int but the "None" string is allowed and interpreted as None
chunk_size    = "None"  # int but the "None" string is allowed and interpreted as None
chunk_overlap = "None"  # int but the "None" string is allowed and interpreted as None
# Templated S3 path to save and load documents collection from
documents_s3_dir = "s3://{s3_bucket}/data/chunked_documents/model_id={emb_model}/chunk_overlap={chunk_overlap}/chunk_size={chunk_size}/max_pages={max_pages}"
documents_jsonl_s3_path = "{documents_s3_dir}/docs.jsonl"
documents_parquet_s3_path = "{documents_s3_dir}/corpus.parquet"

# VECTOR DATABASE -------------------------------------------------------------

chroma_db_local_dir = "chroma_db"
chroma_db_local_path = "{data_dir_path}/{chroma_db_local_dir}" # (templated)
chroma_db_s3_dir = "data/chroma_database"
chroma_db_s3_path = "{s3_bucket}/{chroma_db_s3_dir}" # (templated)
collection_name = "insee_data"
force_rebuild = false

# IR MODEL    -----------------------------------------------------------------

# Embedding model for IR
emb_device = "cuda"
emb_model = "OrdalieTech/Solon-embeddings-large-0.1"

# LLM -------------------------------------------------------------------------

# LLM Model
llm_model = "mistralai/Mistral-7B-Instruct-v0.2"
quantization = false

s3_model_cache_dir = "models/hf_hub"
max_new_tokens = 2000

# EVALUATION ------------------------------------------------------------------

faq_s3_path = "data/FAQ_site/faq.parquet"
faq_s3_uri = "s3://{s3_bucket}/{faq_s3_path}" # (templated)
topk_stats = 3

# INSTRUCTION PROMPT ----------------------------------------------------------

BASIC_RAG_PROMPT_TEMPLATE = """<s>[INST]
    Instruction: Réponds à la question en te basant sur le contexte donné:

    {context}

    Question:
    {question}
    [/INST]"""

RAG_PROMPT_TEMPLATE = """<s>[INST]
    Tu es un assistant spécialisé dans la statistique publique répondant aux questions d'agent de l'INSEE.
    Réponds en Français seulement.
    Utilise les informations obtenues dans le contexte, réponds de manière argumentée à la question posée.
    La réponse doit être développée et citer ses sources.

    Si tu ne peux pas induire ta réponse du contexte, ne réponds pas.
    Voici le contexte sur lequel tu dois baser ta réponse :
    Contexte: {context}
            ---
    Voici la question à laquelle tu dois répondre :
    Question: {question}
    [/INST]"""

# CHATBOT TEMPLATE -------------------------------------------------------

CHATBOT_SYSTEM_INSTRUCTION = """
Tu es un assistant spécialisé dans la statistique publique.
Tu réponds à des questions concernant les données de l'Insee, l'institut national statistique Français.

En utilisant UNIQUEMENT les informations présentes dans le contexte, réponds de manière argumentée à la question posée.
La réponse doit être développée et citer ses sources.

Si tu ne peux pas induire ta réponse du contexte, ne réponds pas.
Réponds en FRANCAIS UNIQUEMENT.

Voici le contexte sur lequel tu dois baser ta réponse :
Contexte:
{context}
---
Voici la question à laquelle tu dois répondre :
Question: {question}
"""

# Data

RAW_DATA = "projet-llm-insee-open-data/data/insee_contact/data_2019.csv"
LS_DATA_PATH = "projet-llm-insee-open-data/data/insee_contact/tasks/"
LS_ANNOTATIONS_PATH = "projet-llm-insee-open-data/data/insee_contact/annotations/"


# Chainlit specific parameters in this section

uvicorn_timeout_keep_alive = 0
cli_message_separator_length = 80
llm_temperature = 1.0
return_full_text = true
do_sample = true
temperature = 0.2
rep_penalty  = 1.1
top_p = 0.8
# reranking_method =

# Only perform the retrieval (no LLM generation)
retriever_only = false



# Parameters (str only) to be templated using the other parameters.
# The order matters: templates may include previously templated parameters
__templated_params__ = [
    "s3_endpoint_url",
    "data_dir_path",
    "logs_dir_path",
    "raw_dataset_uri",
    "rawdata_web4g_uri",
    "rawdata_rmes_uri",
    "documents_s3_dir",
    "documents_jsonl_s3_path",
    "documents_parquet_s3_path",
    "chroma_db_s3_path",
    "chroma_db_local_path",
    "faq_s3_uri",
]
