name: Construction image Docker

on:
  push:
    branches:
      - prepa-unece

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'prepa-unece'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_PERSO }}
          password: ${{ secrets.DOCKERHUB_TOKEN_PERSO }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: linogaliana/llm-statbot:unece
